name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint (Go ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24', 'stable' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Generate mocks
        run: make generate-mocks

      - name: Run golangci-lint (latest)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

  build-test:
    name: Build & Test (Go ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24', 'stable' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true

      - name: Generate mocks
        run: make generate-mocks

      - name: Verify dependencies
        run: go mod tidy && git diff --exit-code go.mod go.sum

      - name: Build
        run: make build

      - name: Test
        run: make test
