name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.24 (or higher)
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      # - name: Run tests
      #   run: |
      #     go test ./...
      #     go mod tidy

      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
